# web-shop-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pacifista-web-shop-pvc
  namespace: funixproductions
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-shop-microservice-deployment
  namespace: 'funixproductions'
  labels:
    app: springboot
    service: web-shop

spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
      service: web-shop
  template:
    metadata:
      namespace: 'funixproductions'
      annotations:
        build-time: "TIME-UPDATE-BUILD-FNG"
      labels:
        app: springboot
        service: web-shop
    spec:
      containers:
        - name: springboot-web-shop
          image: ghcr.io/pacifistamc/pacifista-api-web-shop:latest
          volumeMounts:
            - mountPath: /container/app/
              name: pacifista-shop-storage
          ports:
            - containerPort: 80
          resources:
            limits:
                memory: "1024Mi"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: APP_PORT
              value: '80'
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: postgres-url
                  name: postgres-config-pacifista
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-pacifista
                  key: postgres-port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-pacifista
                  key: postgres-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-pacifista
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-pacifista
                  key: postgres-password
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret-pacifista
                  key: sentry-pacifista-api-key
            - name: DISCORD_WEBHOOK_ALERTS_ID
              valueFrom:
                secretKeyRef:
                  name: discord-secret-pacifista
                  key: discord-webhook-alert-id
            - name: DISCORD_WEBHOOK_ALERTS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-secret-pacifista
                  key: discord-webhook-alert-token
      volumes:
        - name: pacifista-shop-storage
          persistentVolumeClaim:
            claimName: pacifista-web-shop-pvc

---

apiVersion: v1
kind: Service

metadata:
  namespace: 'funixproductions'
  name: web-shop-service

spec:
  type: ClusterIP
  selector:
    app: springboot
    service: web-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
