version: '3'

services:

  mysql:
    image: mariadb:latest
    container_name: pacifista_api_db
    volumes:
      - ./config/init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - pacifista_api_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - pacifista_api_net
    ports:
      - "3307:3306"

  mail:
    image: maildev/maildev
    container_name: pacifista_api_mail
    networks:
      - pacifista_api_net
    ports:
      - "1081:1080"
      - "1026:1025"

  pacifista-api:
    build:
      context: ../../../
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - mail
    container_name: pacifista_api
    hostname: pacifista_api
    networks:
      - pacifista_api_net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
    ports:
      - "9010:9010"

  funixapi:
    build:
      context: ./funix-api
      dockerfile: Dockerfile
      args:
        FUNIX_API_VERSION: ${FUNIX_API_VERSION}
    depends_on:
      - mysql
      - mail
    container_name: funixapi
    hostname: funixapi
    networks:
      - pacifista_api_net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8585:8080"

networks:
  pacifista_api_net:
    driver: bridge

volumes:
  pacifista_api_db: