create table pacifista_warps
(
    id                bigint generated by default as identity primary key,
    created_at        timestamp        not null,
    updated_at        timestamp,
    uuid              varchar(255)     not null constraint UK_warps_public_id unique,
    pitch             real             not null,
    server_type       varchar(255)     not null,
    world_uuid        varchar(255)     not null,
    x                 double precision not null,
    y                 double precision not null,
    yaw               real             not null,
    z                 double precision not null,
    name              varchar(255)     not null,
    player_owner_uuid varchar(255)     not null,
    public_access     boolean          not null,
    type              varchar(255)     not null,
    warp_item         varchar(255)     not null
);
