create table pacifista_box
(
    id               bigint generated by default as identity primary key,
    created_at       timestamp    not null,
    updated_at       timestamp,
    uuid             varchar(255) not null constraint UK_box_public_id unique,
    box_description  varchar(500) not null,
    box_display_name varchar(255) not null,
    box_name         varchar(255) not null constraint UK_box_name unique,
    drop_amount      integer      not null,
    game_mode        varchar(255) not null
);

create table pacifista_box_reward
(
    id              bigint generated by default as identity primary key,
    created_at      timestamp      not null,
    updated_at      timestamp,
    uuid            varchar(255)   not null constraint UK_box_reward_public_id unique,
    item_serialized varchar(50000) not null,
    rarity          real           not null,
    box_id          bigint         not null constraint link_key_box_id references pacifista_box
);

create table pacifista_player_box
(
    id          bigint generated by default as identity primary key,
    created_at  timestamp    not null,
    updated_at  timestamp,
    uuid        varchar(255) not null constraint UK_player_box_public_id unique,
    amount      integer      not null,
    player_uuid varchar(255) not null,
    box_id      bigint       not null constraint link_box_id_player_box references pacifista_box
);

create table pacifista_guilds
(
    id          bigint generated by default as identity primary key,
    created_at  timestamp        not null,
    updated_at  timestamp,
    uuid        varchar(255)     not null constraint UK_guilds_public_id unique,
    description varchar(255)     not null,
    money       double precision not null,
    name        varchar(255)     not null
);

create table pacifista_guilds_experiences
(
    id         bigint generated by default as identity primary key,
    created_at timestamp    not null,
    updated_at timestamp,
    uuid       varchar(255) not null constraint UK_guilds_exp_public_id unique,
    experience integer      not null,
    level      integer      not null,
    guild_id   bigint       not null constraint link_key_guild_id_exp references pacifista_guilds
);

create table pacifista_guilds_homes
(
    id            bigint generated by default as identity primary key,
    created_at    timestamp        not null,
    updated_at    timestamp,
    uuid          varchar(255)     not null constraint UK_guild_home_public_id unique,
    pitch         real             not null,
    server_type   varchar(255)     not null,
    world_uuid    varchar(255)     not null,
    x             double precision not null,
    y             double precision not null,
    yaw           real             not null,
    z             double precision not null,
    public_access boolean          not null,
    guild_id      bigint           not null constraint link_key_guild_id_home references pacifista_guilds
);

create table pacifista_guilds_logs
(
    id          bigint generated by default as identity primary key,
    created_at  timestamp     not null,
    updated_at  timestamp,
    uuid        varchar(255)  not null constraint UK_guild_logs_public_id unique,
    action      varchar(5000) not null,
    player_uuid varchar(255)  not null,
    guild_id    bigint        not null constraint link_key_guild_id_logs references pacifista_guilds
);

create table pacifista_guilds_members
(
    id          bigint generated by default as identity primary key,
    created_at  timestamp    not null,
    updated_at  timestamp,
    uuid        varchar(255) not null constraint UK_guild_members_public_id unique,
    player_uuid varchar(255) not null,
    role        varchar(255) not null,
    guild_id    bigint       not null constraint link_key_guild_id_members references pacifista_guilds
);

create table pacifista_guilds_messages
(
    id          bigint generated by default as identity primary key,
    created_at  timestamp     not null,
    updated_at  timestamp,
    uuid        varchar(255)  not null constraint UK_guild_messages_public_id unique,
    message     varchar(5000) not null,
    player_uuid varchar(255)  not null,
    subject     varchar(255)  not null,
    guild_id    bigint        not null constraint link_key_guild_id_message references pacifista_guilds
);

create table pacifista_role
(
    id                bigint generated by default as identity primary key,
    created_at        timestamp    not null,
    updated_at        timestamp,
    uuid              varchar(255) not null constraint UK_role_public_id unique,
    name              varchar(255) not null constraint UK_name_role_unique unique,
    player_name_color varchar(255) not null,
    power             varchar(255) not null,
    prefix            varchar(255) not null,
    staff_rank        boolean      not null
);

create table pacifista_permission
(
    id         bigint generated by default as identity primary key,
    created_at timestamp    not null,
    updated_at timestamp,
    uuid       varchar(255) not null constraint UK_permission_public_id unique,
    permission varchar(255) not null,
    role_id    bigint       not null constraint link_permission_to_role_id references pacifista_role
);

create table pacifista_player_role
(
    id          bigint generated by default as identity primary key,
    created_at  timestamp    not null,
    updated_at  timestamp,
    uuid        varchar(255) not null constraint UK_player_role_public_id unique,
    player_uuid varchar(255) not null,
    role_id     bigint       not null constraint link_key_role_id_player_role references pacifista_role
);

create table pacifista_player_enderchest_data
(
    id                               bigint generated by default as identity primary key,
    created_at                       timestamp       not null,
    updated_at                       timestamp,
    uuid                             varchar(255)    not null constraint UK_player_enderchest_data_public_id unique,
    enderchest_elite_serialized      varchar(100000) not null,
    enderchest_legendaire_serialized varchar(100000) not null,
    enderchest_mine_serialized       varchar(100000) not null,
    enderchest_paladin_serialized    varchar(100000) not null,
    enderchest_serialized            varchar(100000) not null,
    game_mode                        varchar(255)    not null,
    player_owner_uuid                varchar(255)    not null
);

create table pacifista_player_experience_data
(
    id                bigint generated by default as identity primary key,
    created_at        timestamp    not null,
    updated_at        timestamp,
    uuid              varchar(255) not null constraint UK_player_experience_data_public_id unique,
    exp               real         not null,
    game_mode         varchar(255) not null,
    level             integer      not null,
    player_owner_uuid varchar(255) not null,
    total_experience  integer      not null
);

create table pacifista_player_inventory_data
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp       not null,
    updated_at        timestamp,
    uuid              varchar(255)    not null constraint UK_player_inventory_data_public_id unique,
    armor             varchar(100000) not null,
    game_mode         varchar(255)    not null,
    inventory         varchar(100000) not null,
    player_owner_uuid varchar(255)    not null
);

create table pacifista_player_money_data
(
    id                bigint generated by default as identity primary key,
    created_at        timestamp        not null,
    updated_at        timestamp,
    uuid              varchar(255)     not null constraint UK_player_money_data_public_id unique,
    money             double precision not null,
    player_owner_uuid varchar(255)     not null
);

create table pacifista_sanctions
(
    id                   bigint generated by default as identity primary key,
    created_at           timestamp    not null,
    updated_at           timestamp,
    uuid                 varchar(255) not null constraint UK_sanctions_public_id unique,
    active               boolean      not null,
    expiration_date      timestamp,
    ip_sanction          boolean      not null,
    player_action_ip     varchar(255),
    player_action_uuid   varchar(255),
    player_sanction_ip   varchar(255) not null,
    player_sanction_uuid varchar(255) not null,
    reason               varchar(255) not null,
    sanction_type        varchar(255) not null
);

create table pacifista_warps
(
    id                bigint generated by default as identity primary key,
    created_at        timestamp        not null,
    updated_at        timestamp,
    uuid              varchar(255)     not null constraint UK_warps_public_id unique,
    pitch             real             not null,
    server_type       varchar(255)     not null,
    world_uuid        varchar(255)     not null,
    x                 double precision not null,
    y                 double precision not null,
    yaw               real             not null,
    z                 double precision not null,
    name              varchar(255)     not null,
    player_owner_uuid varchar(255)     not null,
    public_access     boolean          not null,
    type              varchar(255)     not null,
    warp_item         varchar(255)     not null
);
