apiVersion: apps/v1
kind: Deployment

metadata:
  name: support-tickets-microservice-deployment
  namespace: 'pacifista'
  labels:
    app: springboot
    service: support-tickets

spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
      service: support-tickets
  template:
    metadata:
      namespace: 'pacifista'
      annotations:
        build-time: "TIME-UPDATE-BUILD-FNG"
      labels:
        app: springboot
        service: support-tickets
    spec:
      containers:
        - name: springboot-support-tickets
          image: ghcr.io/pacifistamc/pacifista-api-support-tickets:latest
          ports:
            - containerPort: 80
          resources:
            limits:
                memory: "800Mi"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: APP_PORT
              value: '80'
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: postgres-url
                  name: postgres-config
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password

---

apiVersion: v1
kind: Service

metadata:
  namespace: 'pacifista'
  name: support-tickets-service

spec:
  type: ClusterIP
  selector:
    app: springboot
    service: support-tickets
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
