apiVersion: apps/v1
kind: Deployment

metadata:
  name: server-guilds-microservice-deployment
  namespace: 'funixproductions-dev'
  labels:
    app: springboot
    service: server-guilds

spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
      service: server-guilds
  template:
    metadata:
      namespace: 'funixproductions-dev'
      annotations:
        build-time: "TIME-UPDATE-BUILD-FNG"
      labels:
        app: springboot
        service: server-guilds
    spec:
      containers:
        - name: springboot-server-guilds
          image: ghcr.io/pacifistamc/pacifista-api-server-guilds:dev
          ports:
            - containerPort: 80
          resources:
            limits:
                memory: "500Mi"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: APP_PORT
              value: '80'
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: postgres-url
                  name: postgres-config-pacifista
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-pacifista
                  key: postgres-port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-pacifista
                  key: postgres-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-pacifista
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-pacifista
                  key: postgres-password

---

apiVersion: v1
kind: Service

metadata:
  namespace: 'funixproductions-dev'
  name: server-guilds-service

spec:
  type: ClusterIP
  selector:
    app: springboot
    service: server-guilds
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
