apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-news-microservice-deployment
  namespace: 'funixproductions-dev'
  labels:
    app: springboot
    service: web-news

spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
      service: web-news
  template:
    metadata:
      namespace: 'funixproductions-dev'
      annotations:
        build-time: "TIME-UPDATE-BUILD-FNG"
      labels:
        app: springboot
        service: web-news
    spec:
      containers:
        - name: springboot-web-news
          image: ghcr.io/pacifistamc/pacifista-api-web-news:dev
          volumeMounts:
            - mountPath: /container/app/
              name: pacifista-news-storage
          ports:
            - containerPort: 80
          resources:
            limits:
                memory: "400Mi"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: APP_PORT
              value: '80'
            - name: SPRING_PROFILES_ACTIVE
              value: 'dev'
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: postgres-url
                  name: postgres-config-pacifista
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-pacifista
                  key: postgres-port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-pacifista
                  key: postgres-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-pacifista
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-pacifista
                  key: postgres-password
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret-pacifista
                  key: sentry-pacifista-api-key
      volumes:
        - name: pacifista-news-storage
          hostPath:
            path: /root/k3s/data/funixproductions-dev/

---

apiVersion: v1
kind: Service

metadata:
  namespace: 'funixproductions-dev'
  name: web-news-service

spec:
  type: ClusterIP
  selector:
    app: springboot
    service: web-news
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
