CREATE TABLE pacifista_player_chat_message
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    minecraft_uuid     VARCHAR(50)                             NOT NULL,
    minecraft_username VARCHAR(200)                            NOT NULL,
    uuid               VARCHAR(255)                            NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    message            VARCHAR(1000)                           NOT NULL,
    server_type        VARCHAR(255)                            NOT NULL,
    is_command         BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_pacifista_player_chat_message PRIMARY KEY (id)
);

ALTER TABLE pacifista_player_chat_message
    ADD CONSTRAINT uc_pacifista_player_chat_message_uuid UNIQUE (uuid);

CREATE TABLE pacifista_player_data
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    minecraft_uuid                VARCHAR(50)                             NOT NULL,
    minecraft_username            VARCHAR(200)                            NOT NULL,
    uuid                          VARCHAR(255)                            NOT NULL,
    created_at                    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at                    TIMESTAMP WITHOUT TIME ZONE,
    play_time                     BIGINT                                  NOT NULL,
    last_connection               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    first_connection              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    accept_payments               BOOLEAN                                 NOT NULL,
    accept_teleportation          BOOLEAN                                 NOT NULL,
    accept_ping_sound_tag_message BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_pacifista_player_data PRIMARY KEY (id)
);

ALTER TABLE pacifista_player_data
    ADD CONSTRAINT uc_pacifista_player_data_uuid UNIQUE (uuid);

CREATE TABLE pacifista_player_session
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    minecraft_uuid     VARCHAR(50)                             NOT NULL,
    minecraft_username VARCHAR(200)                            NOT NULL,
    uuid               VARCHAR(255)                            NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    connected_at       BIGINT                                  NOT NULL,
    disconnected_at    BIGINT                                  NOT NULL,
    CONSTRAINT pk_pacifista_player_session PRIMARY KEY (id)
);

ALTER TABLE pacifista_player_session
    ADD CONSTRAINT uc_pacifista_player_session_uuid UNIQUE (uuid);
