CREATE TABLE shop_payment
(
    id                        bigint generated by default as identity primary key,
    uuid                      VARCHAR(255) NOT NULL constraint UK_shop_payment_public_id unique,
    created_at                timestamp not null,
    updated_at                timestamp,
    payment_external_order_id VARCHAR(255),
    payment_type              VARCHAR(255) NOT NULL,
    user_id                   VARCHAR(255) NOT NULL
);

CREATE TABLE shop_article_purchases
(
    id            bigint generated by default as identity primary key,
    uuid          VARCHAR(255) NOT NULL constraint UK_shop_article_purchases_public_id unique,
    created_at    timestamp not null,
    updated_at    timestamp,
    quantity      INTEGER NOT NULL,
    payment_id    BIGINT NOT NULL constraint link_key_payment_id_shop_article_purchases references shop_payment,
    article_id    BIGINT NOT NULL constraint link_key_article_id_shop_article_purchases references shop_articles
);