CREATE TABLE job_player (
                            id bigint generated by default as identity primary key,
                            uuid VARCHAR(255) NOT NULL constraint UK_job_player_public_id unique,
                            created_at timestamp not null,
                            updated_at timestamp,
                            player_uuid VARCHAR(255) NOT NULL,
                            game_mode VARCHAR(255) NOT NULL,
                            job_name VARCHAR(255) NOT NULL,
                            exp INTEGER NOT NULL,
                            level INTEGER NOT NULL,
                            points INTEGER NOT NULL,
                            is_active BOOLEAN NOT NULL
);

CREATE TABLE job_player_quest (
                                  id bigint generated by default as identity primary key,
                                  uuid VARCHAR(255) NOT NULL constraint UK_job_player_quest_public_id unique,
                                  created_at timestamp not null,
                                  updated_at timestamp,
                                  player_uuid VARCHAR(255) NOT NULL,
                                  game_mode VARCHAR(255) NOT NULL,
                                  job_name VARCHAR(255) NOT NULL,
                                  quest_name VARCHAR(255) NOT NULL,
                                  finished BOOLEAN NOT NULL,
                                  finished_at timestamp,
                                  json_quest_data TEXT NOT NULL
);

CREATE TABLE job_player_task (
                                 id bigint generated by default as identity primary key,
                                 uuid VARCHAR(255) NOT NULL constraint UK_job_player_task_public_id unique,
                                 created_at timestamp not null,
                                 updated_at timestamp,
                                 player_uuid VARCHAR(255) NOT NULL,
                                 game_mode VARCHAR(255) NOT NULL,
                                 job_name VARCHAR(255) NOT NULL,
                                 amount_required INTEGER NOT NULL,
                                 amount_collected INTEGER NOT NULL,
                                 material_name_to_collect VARCHAR(255) NOT NULL,
                                 json_task_data TEXT,
                                 task_type TEXT
);

CREATE TABLE job_player_task_worker (
                                        id bigint generated by default as identity primary key,
                                        uuid VARCHAR(255) NOT NULL constraint UK_job_player_task_worker_public_id unique,
                                        created_at timestamp not null,
                                        updated_at timestamp,
                                        player_uuid VARCHAR(255) NOT NULL,
                                        game_mode VARCHAR(255) NOT NULL,
                                        job_name VARCHAR(255) NOT NULL,
                                        task_id BIGINT NOT NULL constraint link_key_job_player_task references job_player_task,
                                        participation_amount INTEGER NOT NULL
);