create table job_players_blocks_place
(
    id                               bigint generated by default as identity primary key,
    created_at                       timestamp       not null,
    updated_at                       timestamp,
    uuid                             varchar(255)    not null constraint UK_job_players_blocks_place_public_id unique,
    x                                double precision not null,
    y                                double precision not null,
    z                                double precision not null,
    yaw                              double precision not null,
    pitch                            double precision not null,
    world_uuid                       varchar(255)    not null,
    server_type                      varchar(255)    not null,
    block_type                       varchar(255)    not null
);
