create table pacifista_web_user_link
(
    id                               bigint generated by default as identity primary key,
    created_at                       timestamp       not null,
    updated_at                       timestamp,
    uuid                             varchar(255)    not null constraint UK_pacifista_web_user_link_public_id unique,
    funix_prod_user_id               varchar(255)    not null constraint UK_pacifista_web_user_link_funix_prod_user_id unique,
    minecraft_uuid                   varchar(255)    not null constraint UK_pacifista_web_user_link_minecraft_uuid unique,
    linked                           boolean         not null,
    link_key                         varchar(255)    not null constraint UK_pacifista_web_user_link_link_key unique
);