create table pacifista_announcements
(
    id                               bigint generated by default as identity primary key,
    created_at                       timestamp       not null,
    updated_at                       timestamp,
    uuid                             varchar(255)    not null constraint UK_pacifista_announcements_public_id unique,
    title                            varchar(100)    not null,
    message                          varchar(2000)    not null
);
