create table pacifista_plus_subscription
(
    id                               bigint generated by default as identity primary key,
    created_at                       timestamp       not null,
    updated_at                       timestamp,
    uuid                             varchar(255)    not null constraint UK_pacifista_plus_subscription_public_id unique,
    player_id                        varchar(100)    not null constraint UK_pacifista_plus_subscription_player_id unique,
    expiration_date                  timestamp
);
