create table player_ignores
(
    id                               bigint generated by default as identity primary key,
    created_at                       timestamp       not null,
    updated_at                       timestamp,
    uuid                             varchar(255)    not null constraint UK_player_ignores_public_id unique,
    player_id                        varchar(100)    not null,
    ignored_player_id                varchar(100)    not null
);
