create table pacifista_web_votes
(
    id                               bigint generated by default as identity primary key,
    created_at                       timestamp       not null,
    updated_at                       timestamp,
    uuid                             varchar(255)    not null constraint UK_pacifista_web_votes_public_id unique,
    username                         varchar(100)    not null,
    vote_website                     varchar(100)    not null,
    player_ip                        varchar(100)    not null,
    month_vote                       integer         not null,
    year_vote                        integer         not null,
    vote_validation_date             timestamp,
    next_vote_date                   timestamp
);
