create table pacifista_holograms
(
    id                               bigint generated by default as identity primary key,
    created_at                       timestamp       not null,
    updated_at                       timestamp,
    uuid                             varchar(255)    not null constraint UK_pacifista_holograms_public_id unique,
    text_serialized                  varchar(10000)  not null,
    parent_hologram_id               bigint          constraint link_key_pacifista_holograms_id references pacifista_holograms,
    x                                double precision not null,
    y                                double precision not null,
    z                                double precision not null,
    yaw                              double precision not null,
    pitch                            double precision not null,
    world_uuid                       varchar(255)     not null,
    server_type                      varchar(255)     not null
);
