-- Update_pacifista_news_table

ALTER TABLE pacifista_news DROP COLUMN article_image_url;

ALTER TABLE pacifista_news
    ADD COLUMN article_image_uuid VARCHAR(255),
    ADD COLUMN article_image_low_res_uuid VARCHAR(255);

ALTER TABLE pacifista_news
    ADD COLUMN body_html VARCHAR(200000) NOT NULL,
    ADD COLUMN body_markdown VARCHAR(200000) NOT NULL;

-- Set initial values for new body columns based on existing data, if required
UPDATE pacifista_news
SET body_html = body,
    body_markdown = '';

ALTER TABLE pacifista_news DROP COLUMN body;

ALTER TABLE pacifista_news
    ADD COLUMN draft BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN likes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN comments INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN views INTEGER NOT NULL DEFAULT 0;


-- Create_pacifista_news_images_table

CREATE TABLE pacifista_news_images (
                                       id bigint generated by default as identity primary key,
                                       created_at TIMESTAMP NOT NULL,
                                       updated_at TIMESTAMP,
                                       uuid VARCHAR(255) NOT NULL constraint uk_pacifista_news_images_public_id UNIQUE,
                                       file_name VARCHAR(255) NOT NULL UNIQUE,
                                       file_path VARCHAR(255) NOT NULL UNIQUE,
                                       file_size BIGINT NOT NULL,
                                       file_extension VARCHAR(255) NOT NULL,
                                       news_uuid VARCHAR(255) NOT NULL,
                                       is_low_resolution BOOLEAN NOT NULL
);

-- Create_pacifista_news_likes_table

CREATE TABLE pacifista_news_likes (
                                      id bigint generated by default as identity primary key,
                                      created_at TIMESTAMP NOT NULL,
                                      updated_at TIMESTAMP,
                                      uuid VARCHAR(255) NOT NULL constraint uk_pacifista_news_likes_public_id UNIQUE,
                                      news_id BIGINT NOT NULL constraint fk_pacifista_news_likes_news_id references pacifista_news,
                                      minecraft_username VARCHAR(255) NOT NULL
                                      funixprod_user_id VARCHAR(255) NOT NULL
);

-- Create_pacifista_news_bans_table

CREATE TABLE pacifista_news_bans (
                                     id bigint generated by default as identity primary key,
                                     created_at TIMESTAMP NOT NULL,
                                     updated_at TIMESTAMP,
                                     uuid VARCHAR(255) NOT NULL constraint uk_pacifista_news_bans_public_id UNIQUE,
                                     reason VARCHAR(255) DEFAULT NULL,
                                     minecraft_user_name_banned VARCHAR(255) NOT NULL constraint uk_pacifista_news_bans_minecraft_user_name UNIQUE,
                                     funixprod_user_id_banned VARCHAR(255) NOT NULL constraint uk_pacifista_news_bans_funixprod_user_id UNIQUE,
                                     staff_minecraft_user_name VARCHAR(255) NOT NULL,
                                     staff_funixprod_user_id VARCHAR(255) NOT NULL
);

-- Create_pacifista_news_comments_table

CREATE TABLE pacifista_news_comments (
                                         id bigint generated by default as identity primary key,
                                         created_at TIMESTAMP NOT NULL,
                                         updated_at TIMESTAMP,
                                         uuid VARCHAR(255) NOT NULL constraint uk_pacifista_news_comments_public_id UNIQUE,
                                         news_id BIGINT NOT NULL constraint fk_pacifista_news_comments_news_id references pacifista_news,
                                         minecraft_username VARCHAR(255) NOT NULL,
                                         funixprod_user_id VARCHAR(255) NOT NULL,
                                         parent_id BIGINT DEFAULT NULL constraint fk_pacifista_news_comments_parent_id references pacifista_news_comments,
                                         content VARCHAR(1500) NOT NULL,
                                         likes INT NOT NULL DEFAULT 0
);

-- Create_pacifista_news_comments_likes_table

CREATE TABLE pacifista_news_comments_likes (
                                               id bigint generated by default as identity primary key,
                                               created_at TIMESTAMP NOT NULL,
                                               updated_at TIMESTAMP,
                                               uuid VARCHAR(255) NOT NULL constraint uk_pacifista_news_comments_likes_public_id UNIQUE,
                                               news_id BIGINT NOT NULL constraint fk_pacifista_news_comments_likes_news_id references pacifista_news,
                                               minecraft_username VARCHAR(255) NOT NULL,
                                               funixprod_user_id VARCHAR(255) NOT NULL,
                                               comment_id BIGINT NOT NULL constraint fk_pacifista_news_comments_likes_comment_id references pacifista_news_comments
);
