create table pacifista_sanctions
(
    id                   bigint generated by default as identity primary key,
    created_at           timestamp    not null,
    updated_at           timestamp,
    uuid                 varchar(255) not null constraint UK_sanctions_public_id unique,
    active               boolean      not null,
    expiration_date      timestamp,
    ip_sanction          boolean      not null,
    player_action_ip     varchar(255),
    player_action_uuid   varchar(255),
    player_sanction_ip   varchar(255) not null,
    player_sanction_uuid varchar(255) not null,
    reason               varchar(255) not null,
    sanction_type        varchar(255) not null
);
