create table pacifista_player_enderchest_data
(
    id                               bigint generated by default as identity primary key,
    created_at                       timestamp       not null,
    updated_at                       timestamp,
    uuid                             varchar(255)    not null constraint UK_player_enderchest_data_public_id unique,
    enderchest_elite_serialized      varchar(100000) not null,
    enderchest_legendaire_serialized varchar(100000) not null,
    enderchest_mine_serialized       varchar(100000) not null,
    enderchest_paladin_serialized    varchar(100000) not null,
    enderchest_serialized            varchar(100000) not null,
    game_mode                        varchar(255)    not null,
    player_owner_uuid                varchar(255)    not null
);

create table pacifista_player_experience_data
(
    id                bigint generated by default as identity primary key,
    created_at        timestamp    not null,
    updated_at        timestamp,
    uuid              varchar(255) not null constraint UK_player_experience_data_public_id unique,
    exp               real         not null,
    game_mode         varchar(255) not null,
    level             integer      not null,
    player_owner_uuid varchar(255) not null,
    total_experience  integer      not null
);

create table pacifista_player_inventory_data
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp       not null,
    updated_at        timestamp,
    uuid              varchar(255)    not null constraint UK_player_inventory_data_public_id unique,
    armor             varchar(100000) not null,
    game_mode         varchar(255)    not null,
    inventory         varchar(100000) not null,
    player_owner_uuid varchar(255)    not null
);

create table pacifista_player_money_data
(
    id                bigint generated by default as identity primary key,
    created_at        timestamp        not null,
    updated_at        timestamp,
    uuid              varchar(255)     not null constraint UK_player_money_data_public_id unique,
    money             double precision not null,
    player_owner_uuid varchar(255)     not null
);
