apiVersion: apps/v1
kind: Deployment

metadata:
  name: server-players-sync-microservice-deployment
  namespace: 'pacifista'
  labels:
    app: springboot
    service: server-players-sync

spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
      service: server-players-sync
  template:
    metadata:
      namespace: 'pacifista'
      annotations:
        build-time: "TIME-UPDATE-BUILD-FNG"
      labels:
        app: springboot
        service: server-players-sync
    spec:
      containers:
        - name: springboot-server-players-sync
          image: ghcr.io/pacifistamc/pacifista-api-server-players-sync:latest
          ports:
            - containerPort: 80
          resources:
            limits:
                memory: "800Mi"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: APP_PORT
              value: '80'
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: postgres-url
                  name: postgres-config
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password

---

apiVersion: v1
kind: Service

metadata:
  namespace: 'pacifista'
  name: server-players-sync-service

spec:
  type: ClusterIP
  selector:
    app: springboot
    service: server-players-sync
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: 'pacifista'
  name: server-players-sync-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-players-sync-microservice-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
