apiVersion: apps/v1
kind: Deployment

metadata:
  name: support-tickets-microservice-deployment
  namespace: 'funixproductions-dev'
  labels:
    app: springboot
    service: support-tickets

spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
      service: support-tickets
  template:
    metadata:
      namespace: 'funixproductions-dev'
      annotations:
        build-time: "TIME-UPDATE-BUILD-FNG"
      labels:
        app: springboot
        service: support-tickets
    spec:
      containers:
        - name: springboot-support-tickets
          image: ghcr.io/pacifistamc/pacifista-api-support-tickets:dev
          ports:
            - containerPort: 80
          resources:
            limits:
                memory: "500Mi"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: APP_PORT
              value: '80'
            - name: SPRING_PROFILES_ACTIVE
              value: 'dev'
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: postgres-url
                  name: postgres-config-pacifista
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-pacifista
                  key: postgres-port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-pacifista
                  key: postgres-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-pacifista
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-pacifista
                  key: postgres-password
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret
                  key: sentry-pacifista-api-key

---

apiVersion: v1
kind: Service

metadata:
  namespace: 'funixproductions-dev'
  name: support-tickets-service

spec:
  type: ClusterIP
  selector:
    app: springboot
    service: support-tickets
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
