name: Update production image and publish maven package

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  publish-maven-package:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: import_gpg
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Maven settings
        run: |
          mkdir -p $HOME/.m2
          cp .github/settings.xml $HOME/.m2/settings.xml

      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode clean deploy -T 6
        env:
          MAVEN_USERNAME: ${{ secrets.FUNIXPROD_MVN_REPO_USER }}
          MAVEN_PASSWORD: ${{ secrets.FUNIXPROD_MVN_REPO_TOKEN }}

  build-production-maven:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: import_gpg
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode clean package -T 6

      - name: Publish Package Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-packages
          path: modules/**/target/*.jar

  build-production-images-service:
    needs: build-production-maven
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download Package Artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-packages
          path: modules

      - name: Build pacifista-api docker images
        env:
          IMAGE_TAG: latest
        run: chmod +x ./build-images.sh && ./build-images.sh

  update-kubernetes-cluster:
    needs:
      - build-production-images-service

    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://api.pacifista.fr

    steps:
      - name: Set up kubectl
        uses: azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Update Kubernetes Cluster
        run: cd kubernetes && chmod +x ./deployServices.sh && ./deployServices.sh

  send-success-build-discord-notif:
    needs:
      - update-kubernetes-cluster

    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CI_STATUS }}
          DISCORD_USERNAME: Pacifista-API-Deploy
        uses: Ilshidur/action-discord@master
        with:
          args: '✅ Pacifista-API 🌍**PROD** (api.pacifista.fr) à bien été déployé sur le cluster Kubernetes !'
