name: Update production image pterodactyl

on:
  release:
    types: [created]

jobs:
  build-pterodactyl-image-and-restart-prod:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push pacifista api pterodactyl dockerfile
        run: |
          docker build . --tag ghcr.io/pacifistamc/pacifista-pteroq-api:latest -f pterodactyl.Dockerfile
          docker push ghcr.io/pacifistamc/pacifista-pteroq-api:latest

